import re
jokerRegex = re.compile(r'(Ha){,5}')
mo1 = jokerRegex.search('Ha! HaHa! HaHaHa! HaHaHaHa! HaHaHaHaHa! U mad, batsy bat?')
mo2 = jokerRegex.search('HaHa! HaHaHa! HaHaHaHa! HaHaHaHaHa! U mad, batsy bat?')
mo3 = jokerRegex.search('HaHaHa! HaHaHaHa! HaHaHaHaHa! U mad, batsy bat?')
mo4 = jokerRegex.search('HaHaHaHa! HaHaHaHaHa! U mad, batsy bat?')
mo5 = jokerRegex.search('HaHaHaHaHa! U mad, batsy bat?')
print('Laughs that i\'ve found: ' + mo1.group())
print('Laughs that i\'ve found: ' + mo2.group())
print('Laughs that i\'ve found: ' + mo3.group())
print('Laughs that i\'ve found: ' + mo4.group())
print('Laughs that i\'ve found: ' + mo5.group())

jokerRegex2 = re.compile(r'(Ha){3,5}')
mmo1 = jokerRegex2.search('HaHaHa joker!')
mmo2 = jokerRegex2.search('HaHaHaHa joker!')
mmo3 = jokerRegex2.search('HaHaHaHaHa joker!')
print('2 - Laughs that i\'ve found: ' + mmo1.group())
print('2 - Laughs that i\'ve found: ' + mmo2.group())
print('2 - Laughs that i\'ve found: ' + mmo3.group())