import bs4
exampleFile = open('example.html')
exampleSoup = bs4.BeautifulSoup(exampleFile.read())
elems = exampleSoup.select('#author')
print(type(elems))
print(len(elems))
print(elems[0])
print(elems[0].getText())
print(str(elems[0]))
print(elems[0].attrs)

pElems = exampleSoup.select('p')
print(type(pElems))
print(len(pElems))
print(pElems[0])
print(pElems[0].getText())
print(str(pElems[0]))
print(pElems[0].attrs)
print(pElems[1])
print(pElems[1].getText())
print(str(pElems[1]))
print(pElems[1].attrs)